name: Print Dynamic Info
on: [push]

jobs:
  print-info:
     runs-on: ubuntu-latest
     steps:
       - name: Print User Info 
         run: |
            echo "Hello ${{github.actor}}"
            echo "You pushed to ${{github.ref_name}}"
            echo "from repository ${{github.event.repository.name}}"
            echo "at $(date '+%Y-%m-%d %H:%M %Z')"

# NOTE: Here we Use the ${{ github.xxx }} context variables to access information about the user, branch, and repository.


# OR 
name: Print Dynamic Info
on: [push]

jobs:
  print-info:
     runs-on: ubuntu-latest
     steps:
       - name: Print User Info 
         run: |
            echo "Hello Swapnil"
            echo "You pushed to main"
            echo "from repository cicd"
            echo "at 2026-06-08 10:30 IST"

