name: PR Checks
on:
  pull_request:
    branches:
      - main # it will only run if someone is trying to merge INTO main

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "A pull request was opened or updated!"
        
      - name: Show PR details
        run: |
          echo "This PR is targeting branch: ${{ github.base_ref }}"
          echo "The code is coming from branch: ${{ github.head_ref }}"